version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - cd backend
      - npm install
      - cd ../frontend/frontend
      - npm install

  build:
    commands:
      - echo Building React frontend...
      - npm run build
      - echo Copying frontend dist to backend public directory...
      - mkdir -p ../../backend/public
      - cp -r dist/* ../../backend/public/

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts...
      - cd ../../backend
      - cp ../appspec.yml . # Make sure appspec.yml is in the root directory
      - cp -r ../scripts . # Copy the entire scripts directory

artifacts:
  files:
    - '**/*'
  base-directory: backend
